title: "💬 [Discussion]: "
labels: ["discussion"]
body: |
  ## Topic
  <!-- What would you like to discuss? -->

  ## Context
  <!-- Provide any relevant background information -->

  ## Questions
  <!-- What questions do you have or what would you like to explore? -->

  ## Your Thoughts
  <!-- Share your initial thoughts or perspective -->
