title: "💡 [Idea]: "
labels: ["idea"]
body: |
  ## Idea Description
  <!-- Share your idea for improving ArbFinder Suite -->

  ## Problem it Solves
  <!-- What problem does this idea address? -->

  ## Potential Benefits
  <!-- How would this benefit users? -->

  ## Implementation Thoughts
  <!-- Any thoughts on how this could be implemented? -->

  ## Additional Context
  <!-- Any other information about your idea -->
