title: "🎉 [Show & Tell]: "
labels: ["show-and-tell"]
body: |
  ## What I Built
  <!-- Tell us what you built with ArbFinder Suite -->

  ## How I Use It
  <!-- Describe your use case -->

  ## Screenshots/Demo
  <!-- Share screenshots, videos, or links -->

  ## Technical Details
  <!-- Share any interesting technical details (optional) -->

  ## Challenges and Solutions
  <!-- Any challenges you faced and how you solved them (optional) -->

  ## Advice for Others
  <!-- Any tips for others who want to do something similar? -->
