name: Documentation Improvement
description: Suggest improvements or report issues in documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README
        - API Documentation
        - User Guide
        - Developer Guide
        - Code Comments
        - Architecture Documentation
        - Examples/Tutorials
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong or missing in the current documentation?
      placeholder: The documentation for X doesn't explain...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located? (file path, URL, section)
      placeholder: docs/API.md, section "Authentication"
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should this be improved?
      placeholder: Add explanation about...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or references
    validations:
      required: false
