name: 📚 Documentation
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - User Guide
        - API Documentation
        - Developer Guide
        - Installation Guide
        - Configuration Guide
        - Tutorial
        - README
        - Code Comments
        - Architecture Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What's wrong with the documentation?
      options:
        - Missing information
        - Incorrect information
        - Unclear explanation
        - Outdated content
        - Broken links
        - Typo or grammar
        - Missing example
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation (or where should it be)?
      placeholder: |
        - File: README.md, section "Installation"
        - URL: https://...
        - Missing from: docs/
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Content
      description: What does the documentation currently say (if applicable)?
      placeholder: The current documentation says...
      render: markdown

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: What should the documentation say instead?
      placeholder: I suggest changing it to...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context that would help improve the documentation
      placeholder: This would help users who...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR to fix this documentation issue
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I have provided the location and suggested improvement
          required: true
